// <auto-generated />
using System;
using IPS.Middleware.Infrastructure.Transactions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IPS.Middleware.Infrastructure.Transactions.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    [Migration("20261004125120_Pacs008SubmissionEvidence")]
    partial class Pacs008SubmissionEvidence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IPS.Middleware.Domain.Transactions.OutgoingPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ClaimExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientReference")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrentDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("CurrentIpsInternalCode")
                        .HasColumnType("int");

                    b.Property<string>("CurrentReasonCode")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int>("CurrentSequence")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSource")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CurrentStatusAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int>("EventSequence")
                        .HasColumnType("int")
                        .HasColumnName("LastSequence");

                    b.Property<string>("MessageId")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset?>("NextActionAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProtocolTransactionId")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SignedXml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmissionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmissionResponseJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnsignedXml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimExpiresAtUtc");

                    b.HasIndex("ClientReference")
                        .IsUnique();

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasFilter("[MessageId] IS NOT NULL");

                    b.HasIndex("ProtocolTransactionId")
                        .IsUnique()
                        .HasFilter("[ProtocolTransactionId] IS NOT NULL");

                    b.HasIndex("Direction", "CurrentStatus", "MessageType", "CurrentStatusAtUtc", "Id");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_Claim", "([ClaimToken] IS NULL AND [ClaimExpiresAtUtc] IS NULL) OR ([ClaimToken] IS NOT NULL AND [ClaimExpiresAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Transactions_Preparation", "([MessageId] IS NULL AND [ProtocolTransactionId] IS NULL AND [UnsignedXml] IS NULL AND [SignedXml] IS NULL) OR ([MessageType] = 'pacs.008' AND [MessageId] IS NOT NULL AND [ProtocolTransactionId] IS NOT NULL AND ([SignedXml] IS NULL OR [UnsignedXml] IS NOT NULL))");

                            t.HasCheckConstraint("CK_Transactions_Submission", "([SubmissionJson] IS NULL AND [SubmissionResponseJson] IS NULL) OR ([SubmissionJson] IS NOT NULL AND ISJSON([SubmissionJson]) = 1 AND [MessageType] = 'pacs.008' AND [MessageId] IS NOT NULL AND [ProtocolTransactionId] IS NOT NULL AND [UnsignedXml] IS NOT NULL AND ([SubmissionResponseJson] IS NULL OR ISJSON([SubmissionResponseJson]) = 1))");
                        });
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Events.TransactionEventRow", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.HasKey("TransactionId", "Sequence");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("TransactionEvents", (string)null);
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Events.TransactionEventRow", b =>
                {
                    b.HasOne("IPS.Middleware.Domain.Transactions.OutgoingPayment", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
