// <auto-generated />
using System;
using IPS.Middleware.Infrastructure.Transactions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IPS.Middleware.Infrastructure.Transactions.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    [Migration("20261006190328_OutgoingCamt056")]
    partial class OutgoingCamt056
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IPS.Middleware.Domain.Inbound.IncomingPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateKind")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasComputedColumnSql("CONVERT(varchar(32), 'incoming-payment')", true);

                    b.Property<string>("CoreDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CoreInternalErrorCode")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CoreProcessedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CoreReasonCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoreReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoreStatus")
                        .HasColumnType("int");

                    b.Property<string>("EndToEndId")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("EndToEndIdBytes")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("DATALENGTH([EndToEndId])", true);

                    b.Property<int>("EventSequence")
                        .HasColumnType("int")
                        .HasColumnName("LastSequence");

                    b.Property<int>("FollowUp")
                        .HasColumnType("int");

                    b.Property<bool?>("IpsAccepted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("IpsDecidedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IpsDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpsReasonCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManualReviewReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParticipantBic")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Reversal")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ReversalObservedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Id", "AggregateKind")
                        .IsUnique();

                    b.HasIndex("ParticipantBic", "EndToEndId", "EndToEndIdBytes")
                        .IsUnique();

                    b.ToTable("IncomingPayments", null, t =>
                        {
                            t.HasCheckConstraint("CK_IncomingPayments_Claim", "([ClaimToken] IS NULL AND [ClaimExpiresAtUtc] IS NULL) OR ([ClaimToken] IS NOT NULL AND [ClaimExpiresAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_IncomingPayments_Request", "ISJSON([RequestJson]) = 1");
                        });
                });

            modelBuilder.Entity("IPS.Middleware.Domain.Inbound.IncomingTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateKind")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasComputedColumnSql("CONVERT(varchar(32), 'incoming-transfer')", true);

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("CoreDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("CoreProcessedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CoreReasonCode")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("CoreReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CoreStatus")
                        .HasColumnType("int");

                    b.Property<int>("EventSequence")
                        .HasColumnType("int")
                        .HasColumnName("LastSequence");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("KeyBytes")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("DATALENGTH([Key])", true);

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ManualReviewReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ParticipantBic")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Id", "AggregateKind")
                        .IsUnique();

                    b.HasIndex("ParticipantBic", "Kind", "Key", "KeyBytes")
                        .IsUnique();

                    b.ToTable("IncomingTransfers", null, t =>
                        {
                            t.HasCheckConstraint("CK_IncomingTransfers_Claim", "([ClaimToken] IS NULL AND [ClaimExpiresAtUtc] IS NULL) OR ([ClaimToken] IS NOT NULL AND [ClaimExpiresAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_IncomingTransfers_Request", "ISJSON([RequestJson]) = 1");
                        });
                });

            modelBuilder.Entity("IPS.Middleware.Domain.Transactions.OutgoingPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateKind")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasComputedColumnSql("CONVERT(varchar(32), 'outgoing-payment')", true);

                    b.Property<string>("ClientReference")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrentDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("CurrentIpsInternalCode")
                        .HasColumnType("int");

                    b.Property<string>("CurrentReasonCode")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int>("CurrentSequence")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSource")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CurrentStatusAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EventSequence")
                        .HasColumnType("int")
                        .HasColumnName("LastSequence");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ClientReference")
                        .IsUnique();

                    b.HasIndex("Id", "AggregateKind")
                        .IsUnique();

                    b.HasIndex("CurrentStatus", "MessageType", "CurrentStatusAtUtc", "Id");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Events.AggregateIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.ToTable("AggregateIdentities", null, t =>
                        {
                            t.HasCheckConstraint("CK_AggregateIdentities_Kind", "[Kind] IN ('outgoing-payment', 'incoming-payment', 'incoming-transfer')");
                        });
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Events.TransactionEventRow", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("AggregateKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.HasKey("TransactionId", "Sequence");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("TransactionId", "AggregateKind");

                    b.ToTable("TransactionEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_TransactionEvents_Kind", "([AggregateKind] = 'outgoing-payment' AND [Name] LIKE 'payment.%') OR ([AggregateKind] = 'incoming-payment' AND [Name] LIKE 'incoming-payment.%') OR ([AggregateKind] = 'incoming-transfer' AND [Name] LIKE 'incoming-transfer.%')");
                        });
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Inbound.InboundJournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ClaimExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DuplicateCount")
                        .HasColumnType("bigint");

                    b.Property<string>("HoldReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("IncomingPaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastDuplicateAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<DateTimeOffset?>("NextActionAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OriginalJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParticipantBic")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<bool>("PossibleDuplicate")
                        .HasColumnType("bit");

                    b.Property<string>("RawXml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ReplyCheckpoint")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("IncomingPaymentId");

                    b.HasIndex("ParticipantBic", "Sequence")
                        .IsUnique()
                        .HasFilter("[Sequence] > 0");

                    b.HasIndex("Status", "NextActionAtUtc", "ReceivedAtUtc", "Id");

                    b.ToTable("InboundMessageJournal", null, t =>
                        {
                            t.HasCheckConstraint("CK_InboundJournal_Attachment", "([IncomingPaymentId] IS NULL AND [OriginalJson] IS NULL) OR ([OriginalJson] IS NOT NULL AND ISJSON([OriginalJson]) = 1)");

                            t.HasCheckConstraint("CK_InboundJournal_Claim", "([ClaimToken] IS NULL AND [ClaimExpiresAtUtc] IS NULL) OR ([ClaimToken] IS NOT NULL AND [ClaimExpiresAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_InboundJournal_Duplicates", "[DuplicateCount] >= 0");

                            t.HasCheckConstraint("CK_InboundJournal_Scheduling", "([Status] = 0 AND [NextActionAtUtc] IS NOT NULL) OR ([Status] <> 0 AND [NextActionAtUtc] IS NULL AND [ClaimToken] IS NULL)");

                            t.HasCheckConstraint("CK_InboundJournal_Sequence", "([Status] = 2 AND [HoldReason] IS NOT NULL) OR ([Status] IN (0, 1) AND [Sequence] IS NOT NULL AND [Sequence] > 0 AND [HoldReason] IS NULL)");

                            t.HasCheckConstraint("CK_InboundJournal_Status", "[Status] IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Inbound.IncomingCoreCallRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompletionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Consumed")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<Guid>("OwnerToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasFilter("[Kind] = 0");

                    b.HasIndex("PaymentId", "Kind")
                        .IsUnique()
                        .HasFilter("[Kind] = 3");

                    b.HasIndex("PaymentId", "Number")
                        .IsUnique();

                    b.ToTable("IncomingCoreCalls", null, t =>
                        {
                            t.HasCheckConstraint("CK_IncomingCoreCalls_Kind", "[Kind] IN (0, 1, 2, 3)");

                            t.HasCheckConstraint("CK_IncomingCoreCalls_Request", "([Kind] = 3 AND [RequestJson] IS NOT NULL AND ISJSON([RequestJson]) = 1) OR ([Kind] <> 3 AND [RequestJson] IS NULL)");

                            t.HasCheckConstraint("CK_IncomingCoreCalls_Result", "([CompletionJson] IS NULL AND [Consumed] = 0) OR ([CompletionJson] IS NOT NULL AND ISJSON([CompletionJson]) = 1)");
                        });
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Inbound.IncomingPaymentMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CheckpointVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ClaimExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("FollowUpAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("NextActionAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ReconciliationDeadlineUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("FollowUpAtUtc", "Id");

                    b.HasIndex("NextActionAtUtc", "Id");

                    b.ToTable("IncomingPayments", null, t =>
                        {
                            t.HasCheckConstraint("CK_IncomingPayments_Context", "ISJSON([ContextJson]) = 1");

                            t.HasCheckConstraint("CK_IncomingPayments_FollowUpDeadline", "[FollowUpAtUtc] IS NULL OR ([ReconciliationDeadlineUtc] IS NOT NULL AND [FollowUpAtUtc] <= [ReconciliationDeadlineUtc])");
                        });
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Inbound.IncomingReplyAttemptRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompletionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Consumed")
                        .HasColumnType("bit");

                    b.Property<Guid>("JournalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<Guid>("OwnerToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("JournalId", "Number")
                        .IsUnique();

                    b.ToTable("IncomingReplyAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_IncomingReplyAttempts_Completion", "([CompletionJson] IS NULL AND [Consumed] = 0) OR ([CompletionJson] IS NOT NULL AND ISJSON([CompletionJson]) = 1)");

                            t.HasCheckConstraint("CK_IncomingReplyAttempts_Number", "[Number] > 0");
                        });
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Inbound.IncomingReplyRow", b =>
                {
                    b.Property<Guid>("JournalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EnvelopeJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MessageKind")
                        .HasColumnType("int");

                    b.Property<string>("MessageXml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UnsignedXml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JournalId");

                    b.ToTable("IncomingReplies", null, t =>
                        {
                            t.HasCheckConstraint("CK_IncomingReplies_Envelope", "ISJSON([EnvelopeJson]) = 1");

                            t.HasCheckConstraint("CK_IncomingReplies_Message", "([MessageXml] IS NULL AND [MessageKind] IS NULL AND [Status] = 0) OR ([UnsignedXml] IS NOT NULL AND [MessageXml] IS NOT NULL AND [MessageKind] IN (0,1) AND [Status] IN (1,2,3))");

                            t.HasCheckConstraint("CK_IncomingReplies_Review", "([Status] = 3 AND [ReviewReason] IS NOT NULL) OR ([Status] <> 3 AND [ReviewReason] IS NULL)");

                            t.HasCheckConstraint("CK_IncomingReplies_Status", "[Status] IN (0,1,2,3)");
                        });
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Inbound.IncomingTransferMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ClaimExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DeadlineUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("NextActionAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("NextActionAtUtc", "Id");

                    b.ToTable("IncomingTransfers", (string)null);
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Outgoing.InvestigationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DeadlineUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("Outcome")
                        .HasColumnType("int");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusRequestId")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("TransportFailure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnsignedXml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("StatusRequestId")
                        .IsUnique();

                    b.HasIndex("PaymentId", "Number")
                        .IsUnique();

                    b.ToTable("OutgoingInvestigations", null, t =>
                        {
                            t.HasCheckConstraint("CK_OutgoingInvestigations_State", "[Number] > 0 AND (([Outcome] IS NULL AND [CompletedAtUtc] IS NULL AND [DetailsJson] IS NULL AND [TransportFailure] IS NULL) OR ([Outcome] IS NOT NULL AND [Outcome] BETWEEN 0 AND 3 AND [CompletedAtUtc] IS NOT NULL AND [DetailsJson] IS NOT NULL AND ISJSON([DetailsJson]) = 1))");
                        });
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Outgoing.OutgoingMessageRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int?>("Disposition")
                        .HasColumnType("int");

                    b.Property<string>("Failure")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<Guid?>("InvestigationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageDefinition")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<Guid?>("OriginatingMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ResendId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubmissionOwner")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvestigationId", "Direction")
                        .IsUnique()
                        .HasFilter("[InvestigationId] IS NOT NULL");

                    b.HasIndex("InvestigationId", "PaymentId");

                    b.HasIndex("OriginatingMessageId", "PaymentId");

                    b.HasIndex("PaymentId", "Direction")
                        .IsUnique()
                        .HasFilter("[InvestigationId] IS NULL AND [ResendId] IS NULL");

                    b.HasIndex("ResendId", "Direction")
                        .IsUnique()
                        .HasFilter("[ResendId] IS NOT NULL");

                    b.HasIndex("ResendId", "PaymentId");

                    b.ToTable("OutgoingMessages", null, t =>
                        {
                            t.HasCheckConstraint("CK_OutgoingMessages_Lifecycle", "([InvestigationId] IS NULL OR [ResendId] IS NULL) AND (([Direction] = 0 AND [MessageDefinition] IS NOT NULL AND (([InvestigationId] IS NULL AND [ResendId] IS NULL AND [MessageDefinition] IN ('pacs.008.001.12', 'pacs.009.001.11', 'pacs.004.001.13', 'camt.056.001.11') AND [OriginatingMessageId] IS NULL) OR ([InvestigationId] IS NOT NULL AND [MessageDefinition] = 'pacs.028.001.06' AND [OriginatingMessageId] IS NOT NULL) OR ([ResendId] IS NOT NULL AND [MessageDefinition] IN ('pacs.008.001.12', 'pacs.009.001.11', 'pacs.004.001.13', 'camt.056.001.11') AND [OriginatingMessageId] IS NOT NULL)) AND [Disposition] IS NOT NULL AND [Disposition] IN (0,1) AND [HttpStatusCode] IS NULL AND [HeadersJson] IS NULL AND [ProcessedAtUtc] IS NULL AND [Failure] IS NULL AND (([Status] = 0 AND [StartedAtUtc] IS NULL AND [SubmissionOwner] IS NULL) OR ([Status] = 1 AND [StartedAtUtc] IS NOT NULL AND [SubmissionOwner] IS NOT NULL))) OR ([Direction] = 1 AND [OriginatingMessageId] IS NOT NULL AND [Disposition] IS NULL AND [StartedAtUtc] IS NULL AND [SubmissionOwner] IS NULL AND [HttpStatusCode] IS NOT NULL AND [HttpStatusCode] BETWEEN 100 AND 599 AND [HeadersJson] IS NOT NULL AND ISJSON([HeadersJson]) = 1 AND (([Status] = 2 AND [ProcessedAtUtc] IS NULL AND [Failure] IS NULL) OR ([Status] = 3 AND [ProcessedAtUtc] IS NOT NULL AND [Failure] IS NULL) OR ([Status] = 4 AND [ProcessedAtUtc] IS NOT NULL AND [Failure] IS NOT NULL))))");
                        });
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Outgoing.OutgoingPaymentMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcceptedJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ClaimExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<string>("MessageId")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<DateTimeOffset?>("NextActionAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProtocolTransactionId")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UnsignedXml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimExpiresAtUtc");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasFilter("[MessageId] IS NOT NULL");

                    b.HasIndex("ProtocolTransactionId")
                        .IsUnique()
                        .HasFilter("[ProtocolTransactionId] IS NOT NULL");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_Accepted", "[AcceptedJson] IS NULL OR ([MessageType] IN ('pacs.008', 'pacs.009', 'pacs.004', 'camt.056') AND ISJSON([AcceptedJson]) = 1)");

                            t.HasCheckConstraint("CK_Transactions_Claim", "([ClaimToken] IS NULL AND [ClaimExpiresAtUtc] IS NULL) OR ([ClaimToken] IS NOT NULL AND [ClaimExpiresAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Transactions_Preparation", "([MessageId] IS NULL AND [ProtocolTransactionId] IS NULL AND [UnsignedXml] IS NULL) OR ([MessageType] IN ('pacs.008', 'pacs.009', 'pacs.004', 'camt.056') AND [MessageId] IS NOT NULL AND [ProtocolTransactionId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Outgoing.OutgoingStatusDeliveryRow", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ClaimExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeliveredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastFailure")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("NextAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PayloadVersion")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("PaymentId", "Sequence");

                    b.HasIndex("State", "NextAtUtc", "PaymentId", "Sequence");

                    b.ToTable("OutgoingStatusDeliveries", null, t =>
                        {
                            t.HasCheckConstraint("CK_OutgoingStatusDeliveries_Claim", "([ClaimToken] IS NULL AND [ClaimExpiresAtUtc] IS NULL) OR ([ClaimToken] IS NOT NULL AND [ClaimExpiresAtUtc] IS NOT NULL AND [Attempts] > 0 AND [State] = 0)");

                            t.HasCheckConstraint("CK_OutgoingStatusDeliveries_Payload", "[Sequence] > 0 AND [PayloadVersion] = 1 AND ISJSON([PayloadJson]) = 1 AND [Attempts] >= 0");

                            t.HasCheckConstraint("CK_OutgoingStatusDeliveries_State", "([State] = 0 AND [NextAtUtc] IS NOT NULL AND [DeliveredAtUtc] IS NULL) OR ([State] = 1 AND [NextAtUtc] IS NULL AND [DeliveredAtUtc] IS NOT NULL AND [ClaimToken] IS NULL) OR ([State] = 2 AND [NextAtUtc] IS NULL AND [DeliveredAtUtc] IS NULL AND [ClaimToken] IS NULL)");
                        });
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Outgoing.ResendRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeadlineUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InvestigationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("Outcome")
                        .HasColumnType("int");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransportFailure")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InvestigationId")
                        .IsUnique()
                        .HasFilter("[InvestigationId] IS NOT NULL");

                    b.HasIndex("InvestigationId", "PaymentId");

                    b.HasIndex("PaymentId", "Number")
                        .IsUnique();

                    b.ToTable("OutgoingResends", null, t =>
                        {
                            t.HasCheckConstraint("CK_OutgoingResends_State", "[Number] > 0 AND (([InvestigationId] IS NOT NULL AND [DeadlineUtc] IS NULL) OR ([InvestigationId] IS NULL AND [DeadlineUtc] IS NOT NULL)) AND (([Outcome] IS NULL AND [CompletedAtUtc] IS NULL AND [DetailsJson] IS NULL AND [TransportFailure] IS NULL) OR ([Outcome] IS NOT NULL AND [Outcome] BETWEEN 0 AND 2 AND [CompletedAtUtc] IS NOT NULL AND [DetailsJson] IS NOT NULL AND ISJSON([DetailsJson]) = 1))");
                        });
                });

            modelBuilder.Entity("IPS.Middleware.Domain.Inbound.IncomingPayment", b =>
                {
                    b.HasOne("IPS.Middleware.Infrastructure.Persistence.Inbound.IncomingPaymentMetadata", null)
                        .WithOne("Payment")
                        .HasForeignKey("IPS.Middleware.Domain.Inbound.IncomingPayment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPS.Middleware.Infrastructure.Persistence.Events.AggregateIdentity", null)
                        .WithOne()
                        .HasForeignKey("IPS.Middleware.Domain.Inbound.IncomingPayment", "Id", "AggregateKind")
                        .HasPrincipalKey("IPS.Middleware.Infrastructure.Persistence.Events.AggregateIdentity", "Id", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IPS.Middleware.Domain.Inbound.IncomingTransfer", b =>
                {
                    b.HasOne("IPS.Middleware.Infrastructure.Persistence.Inbound.IncomingTransferMetadata", null)
                        .WithOne("Transfer")
                        .HasForeignKey("IPS.Middleware.Domain.Inbound.IncomingTransfer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPS.Middleware.Infrastructure.Persistence.Events.AggregateIdentity", null)
                        .WithOne()
                        .HasForeignKey("IPS.Middleware.Domain.Inbound.IncomingTransfer", "Id", "AggregateKind")
                        .HasPrincipalKey("IPS.Middleware.Infrastructure.Persistence.Events.AggregateIdentity", "Id", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IPS.Middleware.Domain.Transactions.OutgoingPayment", b =>
                {
                    b.HasOne("IPS.Middleware.Infrastructure.Persistence.Outgoing.OutgoingPaymentMetadata", null)
                        .WithOne("Payment")
                        .HasForeignKey("IPS.Middleware.Domain.Transactions.OutgoingPayment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPS.Middleware.Infrastructure.Persistence.Events.AggregateIdentity", null)
                        .WithOne()
                        .HasForeignKey("IPS.Middleware.Domain.Transactions.OutgoingPayment", "Id", "AggregateKind")
                        .HasPrincipalKey("IPS.Middleware.Infrastructure.Persistence.Events.AggregateIdentity", "Id", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Events.TransactionEventRow", b =>
                {
                    b.HasOne("IPS.Middleware.Infrastructure.Persistence.Events.AggregateIdentity", null)
                        .WithMany()
                        .HasForeignKey("TransactionId", "AggregateKind")
                        .HasPrincipalKey("Id", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Inbound.InboundJournalEntry", b =>
                {
                    b.HasOne("IPS.Middleware.Domain.Inbound.IncomingPayment", null)
                        .WithMany()
                        .HasForeignKey("IncomingPaymentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Inbound.IncomingCoreCallRow", b =>
                {
                    b.HasOne("IPS.Middleware.Domain.Inbound.IncomingPayment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Inbound.IncomingReplyAttemptRow", b =>
                {
                    b.HasOne("IPS.Middleware.Infrastructure.Persistence.Inbound.IncomingReplyRow", null)
                        .WithMany()
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Inbound.IncomingReplyRow", b =>
                {
                    b.HasOne("IPS.Middleware.Infrastructure.Persistence.Inbound.InboundJournalEntry", null)
                        .WithOne()
                        .HasForeignKey("IPS.Middleware.Infrastructure.Persistence.Inbound.IncomingReplyRow", "JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Outgoing.InvestigationRow", b =>
                {
                    b.HasOne("IPS.Middleware.Domain.Transactions.OutgoingPayment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Outgoing.OutgoingMessageRow", b =>
                {
                    b.HasOne("IPS.Middleware.Domain.Transactions.OutgoingPayment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IPS.Middleware.Infrastructure.Persistence.Outgoing.InvestigationRow", null)
                        .WithMany()
                        .HasForeignKey("InvestigationId", "PaymentId")
                        .HasPrincipalKey("Id", "PaymentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IPS.Middleware.Infrastructure.Persistence.Outgoing.OutgoingMessageRow", null)
                        .WithMany()
                        .HasForeignKey("OriginatingMessageId", "PaymentId")
                        .HasPrincipalKey("Id", "PaymentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IPS.Middleware.Infrastructure.Persistence.Outgoing.ResendRow", null)
                        .WithMany()
                        .HasForeignKey("ResendId", "PaymentId")
                        .HasPrincipalKey("Id", "PaymentId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Outgoing.OutgoingStatusDeliveryRow", b =>
                {
                    b.HasOne("IPS.Middleware.Domain.Transactions.OutgoingPayment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Outgoing.ResendRow", b =>
                {
                    b.HasOne("IPS.Middleware.Domain.Transactions.OutgoingPayment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IPS.Middleware.Infrastructure.Persistence.Outgoing.InvestigationRow", null)
                        .WithMany()
                        .HasForeignKey("InvestigationId", "PaymentId")
                        .HasPrincipalKey("Id", "PaymentId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Inbound.IncomingPaymentMetadata", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Inbound.IncomingTransferMetadata", b =>
                {
                    b.Navigation("Transfer")
                        .IsRequired();
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Outgoing.OutgoingPaymentMetadata", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
