// <auto-generated />
using System;
using IPS.Middleware.Infrastructure.Transactions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IPS.Middleware.Infrastructure.Transactions.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    [Migration("20261004162057_InboundReceiptReferences")]
    partial class InboundReceiptReferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IPS.Middleware.Domain.Inbound.IncomingPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AggregateKind")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasComputedColumnSql("CONVERT(varchar(32), 'incoming-payment')", true);

                    b.Property<DateTimeOffset?>("ClaimExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EndToEndId")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("EndToEndIdBytes")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("DATALENGTH([EndToEndId])", true);

                    b.Property<int>("EventSequence")
                        .HasColumnType("int")
                        .HasColumnName("LastSequence");

                    b.Property<DateTimeOffset?>("NextActionAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ParticipantBic")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Id", "AggregateKind")
                        .IsUnique();

                    b.HasIndex("NextActionAtUtc", "RegisteredAtUtc", "Id");

                    b.HasIndex("ParticipantBic", "EndToEndId", "EndToEndIdBytes")
                        .IsUnique();

                    b.ToTable("IncomingPayments", null, t =>
                        {
                            t.HasCheckConstraint("CK_IncomingPayments_Claim", "([ClaimToken] IS NULL AND [ClaimExpiresAtUtc] IS NULL) OR ([ClaimToken] IS NOT NULL AND [ClaimExpiresAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_IncomingPayments_Request", "ISJSON([RequestJson]) = 1");
                        });
                });

            modelBuilder.Entity("IPS.Middleware.Domain.Transactions.OutgoingPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcceptedJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AggregateKind")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasComputedColumnSql("CONVERT(varchar(32), 'outgoing-payment')", true);

                    b.Property<DateTimeOffset?>("ClaimExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientReference")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CurrentDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("CurrentIpsInternalCode")
                        .HasColumnType("int");

                    b.Property<string>("CurrentReasonCode")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int>("CurrentSequence")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSource")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CurrentStatusAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int>("EventSequence")
                        .HasColumnType("int")
                        .HasColumnName("LastSequence");

                    b.Property<string>("MessageId")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset?>("NextActionAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProtocolTransactionId")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SignedXml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmissionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmissionResponseJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnsignedXml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimExpiresAtUtc");

                    b.HasIndex("ClientReference")
                        .IsUnique();

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasFilter("[MessageId] IS NOT NULL");

                    b.HasIndex("ProtocolTransactionId")
                        .IsUnique()
                        .HasFilter("[ProtocolTransactionId] IS NOT NULL");

                    b.HasIndex("Id", "AggregateKind")
                        .IsUnique();

                    b.HasIndex("Direction", "CurrentStatus", "MessageType", "CurrentStatusAtUtc", "Id");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_Accepted", "[AcceptedJson] IS NULL OR ([MessageType] = 'pacs.008' AND ISJSON([AcceptedJson]) = 1)");

                            t.HasCheckConstraint("CK_Transactions_Claim", "([ClaimToken] IS NULL AND [ClaimExpiresAtUtc] IS NULL) OR ([ClaimToken] IS NOT NULL AND [ClaimExpiresAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Transactions_Preparation", "([MessageId] IS NULL AND [ProtocolTransactionId] IS NULL AND [UnsignedXml] IS NULL AND [SignedXml] IS NULL) OR ([MessageType] = 'pacs.008' AND [MessageId] IS NOT NULL AND [ProtocolTransactionId] IS NOT NULL AND ([SignedXml] IS NULL OR [UnsignedXml] IS NOT NULL))");

                            t.HasCheckConstraint("CK_Transactions_Submission", "([SubmissionJson] IS NULL AND [SubmissionResponseJson] IS NULL) OR ([SubmissionJson] IS NOT NULL AND ISJSON([SubmissionJson]) = 1 AND [MessageType] = 'pacs.008' AND [MessageId] IS NOT NULL AND [ProtocolTransactionId] IS NOT NULL AND [UnsignedXml] IS NOT NULL AND ([SubmissionResponseJson] IS NULL OR ISJSON([SubmissionResponseJson]) = 1))");
                        });
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Events.AggregateIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.ToTable("AggregateIdentities", null, t =>
                        {
                            t.HasCheckConstraint("CK_AggregateIdentities_Kind", "[Kind] IN ('outgoing-payment', 'incoming-payment')");
                        });
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Events.TransactionEventRow", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("AggregateKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.HasKey("TransactionId", "Sequence");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("TransactionId", "AggregateKind");

                    b.ToTable("TransactionEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_TransactionEvents_Kind", "([AggregateKind] = 'outgoing-payment' AND [Name] LIKE 'payment.%') OR ([AggregateKind] = 'incoming-payment' AND [Name] LIKE 'incoming-payment.%')");
                        });
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Inbound.InboundJournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ClaimExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DuplicateCount")
                        .HasColumnType("bigint");

                    b.Property<string>("HoldReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("IncomingPaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LastDuplicateAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<DateTimeOffset?>("NextActionAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OriginalJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParticipantBic")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<bool>("PossibleDuplicate")
                        .HasColumnType("bit");

                    b.Property<string>("RawXml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("IncomingPaymentId");

                    b.HasIndex("ParticipantBic", "Sequence")
                        .IsUnique()
                        .HasFilter("[Sequence] > 0");

                    b.HasIndex("Status", "NextActionAtUtc", "ReceivedAtUtc", "Id");

                    b.ToTable("InboundMessageJournal", null, t =>
                        {
                            t.HasCheckConstraint("CK_InboundJournal_Attachment", "([IncomingPaymentId] IS NULL AND [OriginalJson] IS NULL) OR ([OriginalJson] IS NOT NULL AND ISJSON([OriginalJson]) = 1)");

                            t.HasCheckConstraint("CK_InboundJournal_Claim", "([ClaimToken] IS NULL AND [ClaimExpiresAtUtc] IS NULL) OR ([ClaimToken] IS NOT NULL AND [ClaimExpiresAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_InboundJournal_Duplicates", "[DuplicateCount] >= 0");

                            t.HasCheckConstraint("CK_InboundJournal_Scheduling", "([Status] = 0 AND [NextActionAtUtc] IS NOT NULL) OR ([Status] <> 0 AND [NextActionAtUtc] IS NULL AND [ClaimToken] IS NULL)");

                            t.HasCheckConstraint("CK_InboundJournal_Sequence", "([Status] = 2 AND [HoldReason] IS NOT NULL) OR ([Status] IN (0, 1) AND [Sequence] IS NOT NULL AND [Sequence] > 0 AND [HoldReason] IS NULL)");

                            t.HasCheckConstraint("CK_InboundJournal_Status", "[Status] IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("IPS.Middleware.Domain.Inbound.IncomingPayment", b =>
                {
                    b.HasOne("IPS.Middleware.Infrastructure.Persistence.Events.AggregateIdentity", null)
                        .WithOne()
                        .HasForeignKey("IPS.Middleware.Domain.Inbound.IncomingPayment", "Id", "AggregateKind")
                        .HasPrincipalKey("IPS.Middleware.Infrastructure.Persistence.Events.AggregateIdentity", "Id", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IPS.Middleware.Domain.Transactions.OutgoingPayment", b =>
                {
                    b.HasOne("IPS.Middleware.Infrastructure.Persistence.Events.AggregateIdentity", null)
                        .WithOne()
                        .HasForeignKey("IPS.Middleware.Domain.Transactions.OutgoingPayment", "Id", "AggregateKind")
                        .HasPrincipalKey("IPS.Middleware.Infrastructure.Persistence.Events.AggregateIdentity", "Id", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Events.TransactionEventRow", b =>
                {
                    b.HasOne("IPS.Middleware.Infrastructure.Persistence.Events.AggregateIdentity", null)
                        .WithMany()
                        .HasForeignKey("TransactionId", "AggregateKind")
                        .HasPrincipalKey("Id", "Kind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IPS.Middleware.Infrastructure.Persistence.Inbound.InboundJournalEntry", b =>
                {
                    b.HasOne("IPS.Middleware.Domain.Inbound.IncomingPayment", null)
                        .WithMany()
                        .HasForeignKey("IncomingPaymentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
